package Ningyou::Provider::Cpan;
use Data::Dumper;
use File::Basename;
use Moose;
use namespace::autoclean;

# VERSION: generated by DZP::OurPkgVersion

# GLOBAL MANDATORY
# [capn:yare-dzil]
#  source=ningyou:///modules/yare-cpan/src
#  method=makefile-pl|dzil|cpanm|build-pl|cpan   (Default makefile-pl)

# GLOBAL AUX
# require=package:libgit-repository-perl,libgit-wrapper-perl,libterm-shell-perl,libdigest-md5-file-perl,libmoose-perl
# perl5lib-env=/srv/env/env-perl-5-14-2  (this will install in PERL5LIB)
# tmpdir=/tmp  (default)

# THINK
# ;perl5lib=/srv/perl-5.14.2
#;perl7lib-user=c

with 'Ningyou::Debug', 'Ningyou::Verbose', 'Ningyou::Out';

has 'options' => (
    is       => 'rw',
    isa      => 'HashRef',
    reader   => 'get_options',
    writer   => 'set_options',
    default  => sub { return {}; },
    required => 1,
);

my $id = q{ } x 8;

sub install {
    my ( $s, $i ) = @_;
    my $ca = exists $i->{cache}    ? $i->{cache}    : die 'no cache';
    my $iv = exists $i->{object}   ? $i->{object}   : die 'no object';
    my $pr = exists $i->{provider} ? $i->{provider} : die 'no provider';
    my $c  = exists $i->{cfg}      ? $i->{cfg}      : die 'no cfg';
    my $wt = exists $i->{wt}       ? $i->{wt}       : die 'no wt';

    my $mo = $c->{class};
    my $o  = $s->get_options;

    my @cmd = ();
    my $u = Ningyou::Util->new( { options => } );

    my $so = $u->source_to_fqfn(
        { module => $mo, worktree => $wt, source => $c->{'source'} } );
    $s->d("$id so [$so]");
    if ( exists $c->{'perl5lib-env'} and -e $c->{'perl5lib-env'} ) {
        push @cmd, "source " . $c->{'perl5lib-env'} . " && ";
    }

    if ( defined $so and -d $so ) {
        push @cmd, "cd $so &&";
    }
    elsif ( defined $so and -e $so ) {
        my $bn = basename( $so, ( '.tar.gz', '.tgz' ) );
        if ( exists $c->{tmpdir} ) {
            push @cmd, "cd $c->{tmpdir} &&tar xvzf $so&&cd $bn &&";
        }
        else {
            push @cmd, "cd /tmp&&tar xvzf $so&&cd $bn&&";
        }
    }
    elsif ( defined $so ) {
        my $m = "ERROR: in [$mo] defined field [source]"
            . " pointing towards Nirvana:\n$so\n";
        die $m;
    }
    if ( $c->{'method'} eq 'build-pl' ) {
        my $c = "perl Build.PL&&./Build build&&./Build test&&./Build install";
        push @cmd, $c;
    }
    elsif ( $c->{'method'} eq 'dzil' ) {
        push @cmd, "dzil install $so";
    }
    else {
        push @cmd, "perl Makefile.PL&&make&&make test&&make install";
    }

    my $cmd = join q{ }, @cmd;
    return $cmd;
}

sub installed {
    my ( $s, $i ) = @_;
    my $c  = exists $i->{cfg}      ? $i->{cfg}      : die "no [cfg]";
    my $pr = exists $i->{provider} ? $i->{provider} : die "no [provider]";
    my $iv = exists $i->{object}   ? $i->{object}   : die "no [object]";

    # ERROR handling
    if ( not exists $c->{provide} ) {
        my $mo = $c->{class};
        my $m  = "ERROR in configuration! In module [$mo]\n";
        $m .= "at section [$pr:$iv] the [provide] field is missing.\n";
        $m .= "(stopping here)\n";
        die $m;
    }

    # INSTALL check
    my $p = $c->{provide};
    eval { system(qq{perl -e 'require $p;' > /dev/null 2>&1}); };
    my $e = defined $? ? $? : 0;

    return 1 if not $e;
    return 0;
}

1;
__END__
