#!/usr/bin/perl -w
use warnings;
use strict;
use AptPkg::Config '$_config';
use AptPkg::System '$_system';
use AptPkg::Version;

$_config->init;
$_system = $_config->system;
my $vs = $_system->versioning;
my $r0= $vs->compare( '2:0.025-1', '3:0.025-1' );
my $r1= $vs->compare( '2.24-1.2+b3', '2.24-1.2+a3' );
my $r2= $vs->compare( '0.1.32','0.1.32' );
print "r[$r0] [$r1] [$r2]\n";

1;
__END__
